# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: thalamus-thalamus
spec:
  schema:
    apiVersion: v1alpha1
    kind: ThalamusCore
    scope: Namespaced
    spec:
      version: string | default="0.1.0"
      prefix: string | default="thalamus-thalamus"
      namespace: string | default="thalamus"
      repository: object
      insecureRegistry: boolean | default=false
    status:
      ready: ${helmRelease.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
  resources:
    - id: repository
      readyWhen:
        - ${repository.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Repository
        metadata:
          name: ${schema.spec.prefix}-repository
          namespace: ${schema.spec.namespace}
        spec:
          repositorySpec: ${schema.spec.repository}
          interval: 10m

    - id: component
      readyWhen:
        - ${component.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Component
        metadata:
          name: ${schema.spec.prefix}-component
          namespace: ${schema.spec.namespace}
        spec:
          component: github.com/cobaltcore-dev/thalamus/thalamus
          repositoryRef:
            name: ${repository.metadata.name}
          semver: ${schema.spec.version}
          interval: 1m

    - id: chartResource
      readyWhen:
        - ${chartResource.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-resource-chart
          namespace: ${schema.spec.namespace}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: thalamus-chart
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: operatorImage
      readyWhen:
        - ${operatorImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-operator
          namespace: ${schema.spec.namespace}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: operator-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: eppImage
      readyWhen:
        - ${eppImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-epp
          namespace: ${schema.spec.namespace}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: epp-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: ociRepository
      readyWhen:
        - ${ociRepository.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: ${schema.spec.prefix}-oci-repository
          namespace: ${schema.spec.namespace}
        spec:
          interval: 1m0s
          insecure: ${schema.spec.insecureRegistry}
          layerSelector:
            mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
            operation: copy
          url: oci://${chartResource.status.additional.oci.registry}/${chartResource.status.additional.oci.repository}
          ref:
            digest: ${chartResource.status.additional.oci.digest}

    - id: helmRelease
      readyWhen:
        - ${helmRelease.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: thalamus
          namespace: ${schema.spec.namespace}
        spec:
          releaseName: thalamus
          targetNamespace: ${schema.spec.namespace}
          interval: 1m
          timeout: 5m
          chartRef:
            kind: OCIRepository
            name: ${ociRepository.metadata.name}
          values:
            operator:
              image:
                registry: ${operatorImage.status.additional.oci.registry}
                repository: ${operatorImage.status.additional.oci.repository}
                digest: ${operatorImage.status.additional.oci.digest}
            epp:
              image:
                registry: ${eppImage.status.additional.oci.registry}
                repository: ${eppImage.status.additional.oci.repository}
                digest: ${eppImage.status.additional.oci.digest}
