# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

node-feature-discovery:
  enabled: false
gpu-operator:
  enabled: false

thalamus:
  models:
    - slug: tiny-llm
      model: arnir0/Tiny-LLM
      accelerator: cpu
      replicas: 1
      extraArgs:
        - "--max-model-len=512"
        - "--dtype=float32"
        - "--enforce-eager"
      extraEnv:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "4"
      resources:
        requests:
          cpu: "2"
          memory: "6Gi"
        limits:
          cpu: "4"
          memory: "6Gi"

  epp:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
