# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

node-feature-discovery:
  enabled: false
gpu-operator:
  enabled: false

model-server:
  enabled: true
  extraEnvFrom:
    - secretRef:
        name: model-server-ghcr-token
  ocm:
    repositories:
      - name: sample
        type: OCIRegistry
        url: ghcr.io/violog/model-server/models

thalamus:
  models:
    - slug: tiny-llm
      model: arnir0/Tiny-LLM
      accelerator: cpu
      replicas: 1
      extraArgs:
        - "--max-model-len=512"
        - "--dtype=float32"
        - "--enable-auto-tool-choice"
        - "--tool-call-parser=openai"
      extraEnv:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "4"
      resources:
        requests:
          cpu: "2"
          memory: "6Gi"
        limits:
          cpu: "4"
          memory: "6Gi"

    - slug: tiny-model-ocm
      model: arnir0.violog.git/tiny-llm
      hfEndpoint: "http://model-server.model-server.svc.cluster.local:8080"
      accelerator: cpu
      replicas: 1
      extraArgs:
        - "--max-model-len=512"
        - "--dtype=float32"
        - "--enable-auto-tool-choice"
        - "--tool-call-parser=openai"
      extraEnv:
        - name: VLLM_USE_V1
          value: "0"
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "4"
        - name: HF_HUB_ETAG_TIMEOUT
          value: "60"
        - name: HF_HUB_DOWNLOAD_TIMEOUT
          value: "120"
      resources:
        requests:
          cpu: "2"
          memory: "6Gi"
        limits:
          cpu: "4"
          memory: "6Gi"

  epp:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
